BEGIN;

ALTER TABLE catalog_stores
    ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION NULL,
    ADD COLUMN IF NOT EXISTS reviews_count BIGINT NULL,
    ADD COLUMN IF NOT EXISTS open_date DATE NULL;

COMMIT;
