BEGIN;

ALTER TABLE catalog_products
    ADD COLUMN IF NOT EXISTS dimension_height_m DOUBLE PRECISION NULL,
    ADD COLUMN IF NOT EXISTS dimension_width_m DOUBLE PRECISION NULL,
    ADD COLUMN IF NOT EXISTS dimension_depth_m DOUBLE PRECISION NULL;

COMMIT;
